# Generated by Django 3.1 on 2021-03-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0004_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
