# Generated by Django 3.1 on 2021-03-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='library',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.RemoveField(
            model_name='takenbook',
            name='library',
        ),
        migrations.RemoveField(
            model_name='takenbook',
            name='returned',
        ),
        migrations.AlterField(
            model_name='takenbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taken_books', to='task2.book'),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
